version: '3'

services:

  my_zk:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: my_zk
    container_name: my_zk
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: my_zk:2888:3888

  my_kafka_1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: my_kafka_1
    container_name: my_kafka_1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://65.0.4.68:9092,INTERNAL://my_kafka_1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "my_zk:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      TOPIC_AUTO_CREATE : "true"
    depends_on:
      - my_zk

  kafka_ui:
     image: provectuslabs/kafka-ui:latest
     container_name: kafka_ui
     hostname: kafka_ui
     restart: 'no'
     ports:
       - 9100:8080
     environment:
       DYNAMIC_CONFIG_ENABLED: 'true'
     depends_on:
       - my_zk
       - my_kafka_1
